version: '2.1'
services:
  noext:
    #run tests with no external dependencies
    image: mdnwebdocs/kuma_base
    user: ${UID:-0}
    volumes:
      - ./:/app
    command: py.test --nomigrations --junit-xml=/app/test_results/smoke.xml kuma/humans kuma/health
    environment:
      - DATABASE_URL=sqlite:///
      - PYTHONDONTWRITEBYTECODE=1

  test:
    image: mdnwebdocs/kuma_base
    user: ${UID:-0}
    volumes:
      - ./:/app
    command: sh -c "urlwait && py.test --nomigrations --junit-xml=/app/test_results/django.xml kuma"
    depends_on:
      - redis
      - mysql
      - elasticsearch
    environment:
      - DATABASE_URL=mysql://root:kuma@mysql:3306/developer_mozilla_org
      - ES_URLS=elasticsearch:9200
      - REDIS_CACHE_SERVER=redis://redis:6379/3
      - PYTHONDONTWRITEBYTECODE=1
      - URLWAIT_TIMEOUT=300
