version: '2.1'
services:
  worker: &worker
    build:
      context: .
      dockerfile: Dockerfile-base
    environment:
      - DJANGO_SETTINGS_MODULE
      - DEBIAN_FRONTEND
      - CFLAGS

  web:
    <<: *worker

  api:
    <<: *worker

