pipeline:
  enabled: true
  script: "integration-tests"
job:
  dockerfile: "docker/images/integration-tests/Dockerfile"
  selenium: "3.8.1"
  base_url: 'https://developer.mozilla.org'
  tests: "not login"
  maintenance_mode: false
